# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c2d43fb4f0d035948d4b04110276d5944b0f1744e8ae1bb5729b4f37f5a17457129a067c35a44f6a35819d9100d1b756b40b54a0677ba066b05d2486932550

test:
  secret_key_base: 9f5d5ea4999b49ff392bafc53be974bfd2249144404c5cb5fd86d834faa44609e6d5a44268311c3833877a2f63811ea0a0dce56b750f77b9db9f9bd9e662d1e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
